# misc
alias cb='xclip -selection clipboard'
alias f='fg'
alias je='nvim -c "set syntax=json" -'
alias l='ls'
alias la='ls -A'
alias ll='ls -Al'
alias ls='ls --group-directories-first --color=auto'
alias q='exit'
alias ra='source ~/.bash_aliases'
alias v='TERM="" nvim'
alias vim='TERM="" nvim'
alias wireless='nmtui'
alias z='cd'

# shotcuts
alias ......='cd ../../../../..;'
alias .....='cd ../../../..;'
alias ....='cd ../../..;'
alias ...='cd ../..;'
alias ..='cd ..;'
alias d='cd ~/desktop'
alias o='cd ~/downloads'
alias r='cd ~/src/revo'
alias s='cd ~/src'

# git
alias ga='git add'
alias gaa='git add --all'
alias gac='git add --all; git commit'
alias gacm='git add --all; git commit -m'
alias gb='git branch'
alias gc='git commit'
alias gcl='git clone'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcom='git checkout master'
alias gd='git diff'
alias gi='git init'
alias gl='git log'
alias gp='git push'
alias gs='git status'

# vagrant
alias vh='vagrant halt'
alias vs='vagrant ssh'
alias vu='vagrant up'

# ad-hoc webserver
alias ws='python -m SimpleHTTPServer'

# recursively run php linter accross all files in cwd
alias phplint="find . -type f -name '*.php' -exec php -l {} \; | grep -v '^No syntax'"

# exports
# NB: I know it's "wrong" to put this here instead of in .bashrc, but it's more
# convient to manage one file instead of two.

# set the editor
export EDITOR=nvim

# lie about the terminal for the sake of compatibility. Some programs seem not
# to properly support suckless-st otherwise.
export TERM=xterm

# set the DFEAULT_CHEAT_DIR to the cheatsheets in my dotfiles directory
export DEFAULT_CHEAT_DIR=~/src/dotfiles/cheat
